version: '2'
services:
  spring-boot-docker-v2:
    image: spring-boot-docker-v2
    ports:
    - "8080:8080"
    depends_on:
      - pgdocker
  pgdocker:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb